# version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx_proxy
    restart: always
    ports: 
      - "9191:80"
      - "444:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - apache
  apache:
    build: ./php
    container_name: apache_php
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./www:/var/www/html"  # Mount the application code
      - "./php/vhosts:/etc/apache2/sites-enabled"  # Mount custom virtual hosts
    depends_on:
      - mysql

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db1
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "9091:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      
volumes:
  mysql_data: